### ISSUE TITLE
Vi keybindings for up/down reversed

### ISSUE THREAD

**Issue by leongc** [mjrusso/scoot#17]
Issue #12 adds vi keybindings, but the bindings for j/k up/down are reversed. `j` should move the cursor down. `k` should move the cursor up (similar for related modifiers). [man vi](https://www.man7.org/linux/man-pages/man1/vi.1p.html#:~:text=control%3E%2DN%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5Bcount%5D-,j,-%5Bcount%5D%20%3Ccarriage%2Dreturn)

**Comment by mjrusso** [comment]
Fixed in v0.9: https://github.com/mjrusso/scoot/releases/tag/v0.9
