### ISSUE TITLE
unable to move cursor in free style mode in finder.

### ISSUE THREAD

**Issue by withteja** [mjrusso/scoot#27]
First of all thank for this amazing contribution. I love using the app.

Steps to reproduce:

1. Open any .dmg file
2. Do CMD+shift+L
3. vim bindings doesn't work.

this is the only place I see this feature is not working so far. I was able to go mouseless pretty much all the time.
![Screen Shot 2022-07-05 at 4 34 29 AM](https://user-images.githubusercontent.com/30190850/177318544-fd7831ca-0e52-4a26-aff4-5aa79c1e3227.png)

**Comment by withteja** [comment]
dragging and dropping that application was my end goal. I am still unable to use cursor navigation when I opened my DMG file. After several trail and error I found out that it works only when CMD+shift+L is used 3 times on that window. it doesn't work the first 2 times. I get error sound the first 2 times.

**Comment by mjrusso** [comment]
> I get error sound the first 2 times

AFAIK, the only code in Scoot that can trigger an error sound is the following:

https://github.com/mjrusso/scoot/blob/8f7643969ee54600585f298ac7ad1791c5bd8ba1/Scoot/KeyboardInputWindow%2BKeyboard.swift#L199-L201

If Scoot is active and you're using ordinary vi bindings, that code should never be triggered.

That, plus the odd delay (are you sure you need to trigger it exactly 3 times, vs. just waiting long enough before the first time you trigger it?) leads me to believe that there's something else happening on the system when you're opening the DMG. Are you running this on a corporate machine, perhaps with some security scanning software? I wonder if it's scanning the DMG for known malware or something along those lines.

**Comment by mjrusso** [comment]
That aside, from my earlier comment:

>  I'm unable to drag-and-drop in this context.

I have a hunch that it's related to the way that clicks are simulated (#28).

**Comment by mjrusso** [comment]
This issue should be fixed in [v1.2](https://github.com/mjrusso/scoot/releases/tag/v1.2) (see #28); please let me know if you continue to experience any problems.
