### ISSUE TITLE
Add Scoot to Homebrew

### ISSUE THREAD

**Issue by mjrusso** [mjrusso/scoot#38]
(Originally requested by @acicovic in [this comment](https://github.com/mjrusso/scoot/issues/23#issuecomment-1365272989).)

**Comment by mjrusso** [comment]
I've followed the instructions documented [here](https://docs.brew.sh/Adding-Software-to-Homebrew#casks) and submitted a PR: Homebrew/homebrew-cask/pull/141428

**Comment by mjrusso** [comment]
And we're live! https://formulae.brew.sh/cask/scoot

**Comment by acicovic** [comment]
Thanks, I'll try this out on first chance!

**Comment by acicovic** [comment]
Worked fine. Thanks! 🙂
